### ISSUE TITLE
Node can't execute ruby file

### ISSUE THREAD

**Issue by markuswinkler** [chimo/brackets-scss-lint#7]
Hi!

I would love to use your plugin and ran into a strange error.
It's probably incredibly basic because I couldn't find any answer on the net,
despite searching for a while.

I am running Mac OS 10.10.4, ruby installed via RVM (2.2.1),
scss_lint gem installed.

The error message from scss lint hints that it ignores the RVM version
and tries to pull the gem from the system ruby version (if I am reading that
correctly). scss-lint runs fine from the comment line (and I set the scsslint.gemDir
in the preferences file).
Does this sound familiar? Error message below.

SCSS Lint terminated with error: Error: Command failed: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- scss_lint (LoadError) from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /Users/markus/.rvm/gems/ruby-2.2.1/gems/scss_lint-0.40.1/bin/scss-lint:3:in `<main>'	

Thanks for your help,
Markus

**Comment by markuswinkler** [comment]
Found it! Turns out it's very MacOS specific.

For GUI programs the default shell environment scripts are ignored, and therefore
RVM managed ruby versions.

The workaround is to define them via launchctl. Those values are gone
though after a reboot, so I put them in .bash_profile since I open a shell anyhow all the time, see below.
-------------
launchctl setenv GEM_HOME /Users/markus/.rvm/gems/ruby-2.2.1
launchctl setenv GEM_PATH /Users/markus/.rvm/gems/ruby-2.2.1:/Users/markus/.rvm/gems/ruby-2.2.1@global
-------------
All more permanent solutions (e.g. launchd.conf) don't work anymore in 10.10.
Hope that helps anyone who ran into a similar issue.

**Comment by YayConnolly** [comment]
Helped me, thank you! This one was frustrating!
